# AZYC001001 Backtest Demo
Run the strategy and inspect metrics/artifacts.

In [4]:
from Modules import run_backtest
result = run_backtest('Modules/config.yaml')
result['metrics']

,total_pnl,max_drawdown,trade_count,put_sell_count,call_sell_count,assignment_count,call_away_count,win_rate_cycle,avg_cycle_days
0,5104.0,-2685.0,13,5,2,1,1,1.0,88.475521

In [7]:
import Modules
# 确保使用函数而不是模块
analysis = Modules.analyze(result['artifacts_path'])
analysis['metrics']

,total_pnl,max_drawdown,trade_count,put_sell_count,call_sell_count,assignment_count,call_away_count,win_rate_cycle,avg_cycle_days
0,5104.0,-2685.0,13,5,2,1,1,1.0,88.475521